//Practical 1.3

fun main() {
    println("Student Enrollment: ")
    val enno = readln()
    println("Student Name: ")
    val name = readln()
    println("Student Branch: ")
    val branch = readln()
    println("Student Class: ")
    val cls = readln()
    println("Student Batch: ")
    val batch = readln()
    println("Student College Name: ")
    val Clg_name = readln()
    println("Student University Name: ")
    val Uni_name = readln()
    println("Student Age: ")
    val Age = readln()
    println()
    println("******************************")
    println()
    println("Students Data")
    println("Student Enrollment: $enno")
    println("Student Name: $name")
    println("Student Branch: $branch")
    println("Student Class: $cls")
    println("Student Batch: $batch")
    println("Student College Name: $Clg_name")
    println("Student University Name: $Uni_name")
    println("Student Age: $Age")
}